"""Initial migration

Revision ID: 70d8238f13fe
Revises: 
Create Date: 2025-11-18 01:08:13.395919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d8238f13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('入退室_出席記録', schema=None) as batch_op:
        batch_op.alter_column('入室日時',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_入退室_出席記録_学生番号'), ['学生番号'], unique=False)
        batch_op.create_index(batch_op.f('ix_入退室_出席記録_記録日'), ['記録日'], unique=False)

    with op.batch_alter_table('学生マスタ', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_学生マスタ_学年'), ['学年'], unique=False)
        batch_op.create_index(batch_op.f('ix_学生マスタ_学科ID'), ['学科ID'], unique=False)
        batch_op.create_index(batch_op.f('ix_学生マスタ_学籍番号'), ['学籍番号'], unique=False)
        batch_op.create_index(batch_op.f('ix_学生マスタ_期'), ['期'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('学生マスタ', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_学生マスタ_期'))
        batch_op.drop_index(batch_op.f('ix_学生マスタ_学籍番号'))
        batch_op.drop_index(batch_op.f('ix_学生マスタ_学科ID'))
        batch_op.drop_index(batch_op.f('ix_学生マスタ_学年'))

    with op.batch_alter_table('入退室_出席記録', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_入退室_出席記録_記録日'))
        batch_op.drop_index(batch_op.f('ix_入退室_出席記録_学生番号'))
        batch_op.alter_column('入室日時',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
